### ISSUE TITLE
Add more default spells

### ISSUE THREAD

**Issue by Niphyr** [Twintop/CdrLogger#9]
Side note, might also be worth adding comments beside each item/spell entry to quickly find them

All priest:

- 325013 - Boon of the Ascended

Resto Shaman:

- 5394 - Healing Stream Totem 
- 108280 - Healing Tide Totem
- 16191 - Mana Tide Totem
- 98008 - Spirit Link Totem

Feral Druid:

- 106951 - Berserk
- 102543 - Incarnation: King of the Jungle

**Comment by Twintop** [comment]
One note, the comment with the spell names will only be present for entries in the source. Any stored off values won't have this (no way to add it that I know of, either).
